FROM rust:1.97.0-slim-bookworm AS builder

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
COPY api ./api
COPY cli ./cli
COPY entity ./entity
COPY migrations ./migrations
COPY src ./src

RUN cargo build --release -p praxis-live

FROM scratch
COPY --from=builder /app/target/release/praxis-live /praxis-live
