FROM node:24.18.0-bookworm-slim AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY tsconfig.json tsconfig.app.json tsconfig.node.json tsconfig.e2e.json ./
COPY vite.config.ts components.json ./
COPY view ./view

RUN npm run build

FROM scratch
COPY --from=builder /app/view/dist /
